<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E2QB3MJH" failures="2" tests="3" name="Default test" time="78.757" errors="0" timestamp="2024-07-23T23:24:13 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="24.352"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.422">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;[Login Successfully]&amp;gt; but was:&amp;lt;[]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[Login Successfully]> but was:<[]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at com.orangehrm.utilities.CommonObjects.verifyTextByContainText(CommonObjects.java:209)
at com.orangehrm.stepDefination.LoginStepDefination.verify_popup_mesaage(LoginStepDefination.java:68)
at ✽.verify popup mesaage "Login Successfully".(file:///D:/AutomationWorkspace/AutomationProjects/DemoOrangeHRM/src/test/resources/Features/LoginTestWithMore.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="30.519">
    <failure type="java.lang.AssertionError" message=" &amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt; Expected and Actual not matching Login Successfully">
      <![CDATA[java.lang.AssertionError:  >>>>>> Expected and Actual not matching Login Successfully
at org.junit.Assert.fail(Assert.java:89)
at com.orangehrm.stepDefination.LoginStepDefination.verify_popup_mesaage(LoginStepDefination.java:72)
at ✽.verify popup mesaage "Login Successfully".(file:///D:/AutomationWorkspace/AutomationProjects/DemoOrangeHRM/src/test/resources/Features/LoginTestWithMore.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
